CREATE TABLE CHOCOLATE_DATA (
  ID INT AUTO_INCREMENT,
  COMPANY VARCHAR(255),
  NAME VARCHAR(255),
  REF VARCHAR(255),
  REVIEW_DATE VARCHAR(32),
  COCOA_PERCENTAGE VARCHAR(6),
  COMPANY_LOCATION VARCHAR(255),
  RATING VARCHAR(10),
  BOARD_BEAN_ORIGIN VARCHAR(255),
  RECORD_TIMESTAMP VARCHAR(255)
);